export interface IForm{
  Title?:string;
   Id?:string;
   Modified?:any;
   Created?:any;
   EditorId?:string;
   AuthorId?:string;
   Yes?:boolean;
   userId?:string;
   choice?:string;
   hyper?:string;
   calculated?:string;
   lookupId?:string;
   Date?:string;
   Versions?:string;
multiline?:string;
multilinrrich?:string;
Metadata?:any;
}
